apiVersion: v1
kind: Service
metadata:
  name: aplicacao-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    name: aplicacao-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aplicacao-pod
  template:
    metadata:
      labels:
        name: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80
